# Generated by Django 4.2.1 on 2023-11-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="thumbnail",
            field=models.ImageField(blank=True, default="default.png", upload_to=""),
        ),
    ]
